query NavigationLinkList($location: String) {
  navigation_links(sort: ["sort"], filter: { location: { _eq: $location } }) {
    id
    route
    display_tag
    target
    button
    translations {
      title
      language_code {
        code
      }
    }
  }
}
