<script setup lang='ts'>

import { useQuery } from '@vue/apollo-composable'
import ProjectPageListQuery from '~/graphql/ProjectPageList.query';
import { ProjectPageList, ProjectPageListVariables } from '../../../graphql/generated/ProjectPageList';
/**
 * Types ProjectList & ProjectListVariables were automatically generated by running
 * "yarn run gql-gen", which executes the apollo codegen command. Apollo searches
 * all query files inside ./graphql and generates typescript files for typed queries.
 */
const { loading, error, result } = 
    useQuery<ProjectPageList, ProjectPageListVariables>(ProjectPageListQuery, {
        lang: 'de-DE', // use locale in future
    });

</script>

<template>
    <div class="project-grid" v-if="result?.project_pages">
        <project-grid-card
            v-for="projectPage in result?.project_pages"
            :key="projectPage.id"
            :project-page="projectPage"/>
        <project-grid-card
            v-for="projectPage in result?.project_pages"
            :key="projectPage.id"
            :project-page="projectPage"/>
        <project-grid-card
            v-for="projectPage in result?.project_pages"
            :key="projectPage.id"
            :project-page="projectPage"/>
        <project-grid-card
            v-for="projectPage in result?.project_pages"
            :key="projectPage.id"
            :project-page="projectPage"/>
    </div>
</template>

<style scoped lang='scss'>
    .project-grid{

        width: 100%;
        max-width: 1200px;
        min-height: 80vh;

        display: grid;
        grid-template-columns: repeat( auto-fit, minmax(350px, 1fr) );

        gap: 30px;
    }
</style>