query DownloadPagesByHash($hash: String) 
{
  download_pages(filter: { hash: {_eq: $hash} })
  {
    id
    hash
    title
    preview
    download_url
    download
    version
    hero {
      id
    }
    project {
      background_color
      text_color
      accent_color
    }
    preview_media{
      external_id
      title
    }

    background_color
    text_color
    accent_color
  }
}