query DownloadPagesByHash($hash: String) 
{
  download_pages(filter: { hash: {_eq: $hash} })
  {
    id
    hash
    title
    preview
    download_url
    download
    version
    hero {
      id
    }
    preview_media{
      external_id
    }
  }
}