#!/usr/bin/env python3
"""Regenerate the embedded @font-face include.

wkhtmltopdf resolves fonts only through fontconfig, and headless Chromium only
sees whatever the container has installed — which, before the image started
shipping `fonts-inter`, was six DejaVu faces and nothing else. Embedding the
webfont as base64 removes the question entirely: the same bytes travel with the
document, so a browser preview, a server-side PDF and an emailed attachment all
set the same type.

    python3 tools/embed_fonts.py
"""

import base64
import pathlib

WEIGHTS = (400, 500, 600, 700)
HERE = pathlib.Path(__file__).resolve().parent
FONTS = HERE / "fonts"
OUT = HERE.parent / "docs" / "templates" / "includes" / "_fonts.html"


def main():
	faces = []
	for weight in WEIGHTS:
		data = (FONTS / f"Inter-{weight}.woff2").read_bytes()
		faces.append(
			"@font-face{font-family:'Inter';font-style:normal;font-weight:%d;"
			"font-display:block;src:url(data:font/woff2;base64,%s) format('woff2')}"
			% (weight, base64.b64encode(data).decode())
		)
	OUT.write_text(
		"{#- GENERATED by tools/embed_fonts.py — Inter, SIL OFL 1.1 (tools/fonts/OFL.txt).\n"
		"   Embedded so the type survives wkhtmltopdf, headless Chromium and Safari alike. -#}\n"
		"<style>\n" + "\n".join(faces) + "\n</style>\n",
		encoding="utf-8",
	)
	print(f"{OUT}: {len(WEIGHTS)} weights, {OUT.stat().st_size} bytes")


if __name__ == "__main__":
	main()
